// Mocking the console error - the `warn` function will not log error out
console.error = jest.fn()
